---
config:
  theme: default
  look: classic
  flowchart:
    defaultRenderer: "elk"
title: entities
---
flowchart TB
  v0@{shape: rounded, label: "aliquoting_procedure_templates"}
  style v0 rx: 3px, ry: 3px 
  v1@{shape: rounded, label: "aliquoting_procedures"}
  style v1 rx: 3px, ry: 3px 
  v2@{shape: rounded, label: "asset_compatibility_rules"}
  style v2 rx: 3px, ry: 3px 
  v3@{shape: rounded, label: "asset_models"}
  style v3 rx: 3px, ry: 3px 
  v4@{shape: rounded, label: "assets"}
  style v4 rx: 3px, ry: 3px 
  v5@{shape: rounded, label: "ball_mill_machine_models"}
  style v5 rx: 3px, ry: 3px 
  v6@{shape: rounded, label: "ball_mill_machines"}
  style v6 rx: 3px, ry: 3px 
  v7@{shape: rounded, label: "ball_mill_procedure_templates"}
  style v7 rx: 3px, ry: 3px 
  v8@{shape: rounded, label: "ball_mill_procedures"}
  style v8 rx: 3px, ry: 3px 
  v9@{shape: rounded, label: "bead_models"}
  style v9 rx: 3px, ry: 3px 
  v10@{shape: rounded, label: "brands"}
  style v10 rx: 3px, ry: 3px 
  v11@{shape: rounded, label: "camera_models"}
  style v11 rx: 3px, ry: 3px 
  v12@{shape: rounded, label: "cameras"}
  style v12 rx: 3px, ry: 3px 
  v13@{shape: rounded, label: "centrifuge_models"}
  style v13 rx: 3px, ry: 3px 
  v14@{shape: rounded, label: "centrifuge_procedure_templates"}
  style v14 rx: 3px, ry: 3px 
  v15@{shape: rounded, label: "centrifuge_procedures"}
  style v15 rx: 3px, ry: 3px 
  v16@{shape: rounded, label: "centrifuges"}
  style v16 rx: 3px, ry: 3px 
  v17@{shape: rounded, label: "commercial_ball_mill_machine_lots"}
  style v17 rx: 3px, ry: 3px 
  v18@{shape: rounded, label: "commercial_ball_mill_machine_models"}
  style v18 rx: 3px, ry: 3px 
  v19@{shape: rounded, label: "commercial_camera_lots"}
  style v19 rx: 3px, ry: 3px 
  v20@{shape: rounded, label: "commercial_camera_models"}
  style v20 rx: 3px, ry: 3px 
  v21@{shape: rounded, label: "commercial_centrifuge_lots"}
  style v21 rx: 3px, ry: 3px 
  v22@{shape: rounded, label: "commercial_centrifuge_models"}
  style v22 rx: 3px, ry: 3px 
  v23@{shape: rounded, label: "commercial_freeze_dryer_lots"}
  style v23 rx: 3px, ry: 3px 
  v24@{shape: rounded, label: "commercial_freeze_dryer_models"}
  style v24 rx: 3px, ry: 3px 
  v25@{shape: rounded, label: "commercial_freezer_lots"}
  style v25 rx: 3px, ry: 3px 
  v26@{shape: rounded, label: "commercial_freezer_models"}
  style v26 rx: 3px, ry: 3px 
  v27@{shape: rounded, label: "commercial_geopositioning_device_lots"}
  style v27 rx: 3px, ry: 3px 
  v28@{shape: rounded, label: "commercial_geopositioning_device_models"}
  style v28 rx: 3px, ry: 3px 
  v29@{shape: rounded, label: "commercial_product_lots"}
  style v29 rx: 3px, ry: 3px 
  v30@{shape: rounded, label: "commercial_products"}
  style v30 rx: 3px, ry: 3px 
  v31@{shape: rounded, label: "container_compatibility_rules"}
  style v31 rx: 3px, ry: 3px 
  v32@{shape: rounded, label: "container_models"}
  style v32 rx: 3px, ry: 3px 
  v33@{shape: rounded, label: "container_sealer_models"}
  style v33 rx: 3px, ry: 3px 
  v34@{shape: rounded, label: "container_sealing_procedure_templates"}
  style v34 rx: 3px, ry: 3px 
  v35@{shape: rounded, label: "container_sealing_procedures"}
  style v35 rx: 3px, ry: 3px 
  v36@{shape: rounded, label: "containers"}
  style v36 rx: 3px, ry: 3px 
  v37@{shape: rounded, label: "digital_asset_models"}
  style v37 rx: 3px, ry: 3px 
  v38@{shape: rounded, label: "digital_assets"}
  style v38 rx: 3px, ry: 3px 
  v39@{shape: rounded, label: "disposal_procedure_templates"}
  style v39 rx: 3px, ry: 3px 
  v40@{shape: rounded, label: "disposal_procedures"}
  style v40 rx: 3px, ry: 3px 
  v41@{shape: rounded, label: "fractioning_procedure_templates"}
  style v41 rx: 3px, ry: 3px 
  v42@{shape: rounded, label: "fractioning_procedures"}
  style v42 rx: 3px, ry: 3px 
  v43@{shape: rounded, label: "freeze_dryer_models"}
  style v43 rx: 3px, ry: 3px 
  v44@{shape: rounded, label: "freeze_dryers"}
  style v44 rx: 3px, ry: 3px 
  v45@{shape: rounded, label: "freeze_drying_procedure_templates"}
  style v45 rx: 3px, ry: 3px 
  v46@{shape: rounded, label: "freeze_drying_procedures"}
  style v46 rx: 3px, ry: 3px 
  v47@{shape: rounded, label: "freezer_models"}
  style v47 rx: 3px, ry: 3px 
  v48@{shape: rounded, label: "freezers"}
  style v48 rx: 3px, ry: 3px 
  v49@{shape: rounded, label: "freezing_procedure_templates"}
  style v49 rx: 3px, ry: 3px 
  v50@{shape: rounded, label: "freezing_procedures"}
  style v50 rx: 3px, ry: 3px 
  v51@{shape: rounded, label: "geopositioning_device_models"}
  style v51 rx: 3px, ry: 3px 
  v52@{shape: rounded, label: "geopositioning_devices"}
  style v52 rx: 3px, ry: 3px 
  v53@{shape: rounded, label: "geopositioning_procedure_templates"}
  style v53 rx: 3px, ry: 3px 
  v54@{shape: rounded, label: "geopositioning_procedures"}
  style v54 rx: 3px, ry: 3px 
  v55@{shape: rounded, label: "harvesting_procedure_templates"}
  style v55 rx: 3px, ry: 3px 
  v56@{shape: rounded, label: "harvesting_procedures"}
  style v56 rx: 3px, ry: 3px 
  v57@{shape: rounded, label: "namespaced_ownables"}
  style v57 rx: 3px, ry: 3px 
  v58@{shape: rounded, label: "namespaces"}
  style v58 rx: 3px, ry: 3px 
  v59@{shape: rounded, label: "next_procedure_templates"}
  style v59 rx: 3px, ry: 3px 
  v60@{shape: rounded, label: "ownables"}
  style v60 rx: 3px, ry: 3px 
  v61@{shape: rounded, label: "owners"}
  style v61 rx: 3px, ry: 3px 
  v62@{shape: rounded, label: "packaging_models"}
  style v62 rx: 3px, ry: 3px 
  v63@{shape: rounded, label: "packaging_procedure_templates"}
  style v63 rx: 3px, ry: 3px 
  v64@{shape: rounded, label: "packaging_procedures"}
  style v64 rx: 3px, ry: 3px 
  v65@{shape: rounded, label: "parent_procedure_templates"}
  style v65 rx: 3px, ry: 3px 
  v66@{shape: rounded, label: "personal_protective_equipment_models"}
  style v66 rx: 3px, ry: 3px 
  v67@{shape: rounded, label: "personal_protective_equipments"}
  style v67 rx: 3px, ry: 3px 
  v68@{shape: rounded, label: "photograph_procedure_templates"}
  style v68 rx: 3px, ry: 3px 
  v69@{shape: rounded, label: "photograph_procedures"}
  style v69 rx: 3px, ry: 3px 
  v70@{shape: rounded, label: "photographs"}
  style v70 rx: 3px, ry: 3px 
  v71@{shape: rounded, label: "physical_asset_models"}
  style v71 rx: 3px, ry: 3px 
  v72@{shape: rounded, label: "physical_assets"}
  style v72 rx: 3px, ry: 3px 
  v73@{shape: rounded, label: "pouring_procedure_templates"}
  style v73 rx: 3px, ry: 3px 
  v74@{shape: rounded, label: "pouring_procedures"}
  style v74 rx: 3px, ry: 3px 
  v75@{shape: rounded, label: "procedure_templates"}
  style v75 rx: 3px, ry: 3px 
  v76@{shape: rounded, label: "procedures"}
  style v76 rx: 3px, ry: 3px 
  v77@{shape: rounded, label: "sample_models"}
  style v77 rx: 3px, ry: 3px 
  v78@{shape: rounded, label: "sample_source_models"}
  style v78 rx: 3px, ry: 3px 
  v79@{shape: rounded, label: "sample_sources"}
  style v79 rx: 3px, ry: 3px 
  v80@{shape: rounded, label: "samples"}
  style v80 rx: 3px, ry: 3px 
  v81@{shape: rounded, label: "storage_procedure_templates"}
  style v81 rx: 3px, ry: 3px 
  v82@{shape: rounded, label: "storage_procedures"}
  style v82 rx: 3px, ry: 3px 
  v83@{shape: rounded, label: "supernatant_procedure_templates"}
  style v83 rx: 3px, ry: 3px 
  v84@{shape: rounded, label: "supernatant_procedures"}
  style v84 rx: 3px, ry: 3px 
  v85@{shape: rounded, label: "teams"}
  style v85 rx: 3px, ry: 3px 
  v86@{shape: rounded, label: "users"}
  style v86 rx: 3px, ry: 3px 
  v87@{shape: rounded, label: "volume_measuring_device_models"}
  style v87 rx: 3px, ry: 3px 
  v88@{shape: rounded, label: "volume_measuring_devices"}
  style v88 rx: 3px, ry: 3px 
  v89@{shape: rounded, label: "volumetric_container_models"}
  style v89 rx: 3px, ry: 3px 
  v90@{shape: rounded, label: "volumetric_containers"}
  style v90 rx: 3px, ry: 3px 
  v91@{shape: rounded, label: "weighed_container_models"}
  style v91 rx: 3px, ry: 3px 
  v92@{shape: rounded, label: "weighing_device_models"}
  style v92 rx: 3px, ry: 3px 
  v93@{shape: rounded, label: "weighing_devices"}
  style v93 rx: 3px, ry: 3px 
  v94@{shape: rounded, label: "weighing_procedure_templates"}
  style v94 rx: 3px, ry: 3px 
  v95@{shape: rounded, label: "weighing_procedures"}
  style v95 rx: 3px, ry: 3px 
  v96@{shape: rounded, label: "entities"}
  style v96 rx: 3px, ry: 3px 
  v0 ---> v75
  v0 ---> v87
  v0 ---> v89
  v1 ---> v0
  v1 ---> v76
  v1 ---> v87
  v1 ---> v88
  v1 ---> v90
  v2 ---> v3
  v2 ---> v60
  v3 ---> v3
  v3 ---> v57
  v4 ---> v3
  v4 ---> v57
  v5 ---> v71
  v6 ---> v4
  v6 ---> v17
  v6 ---> v72
  v7 ---> v2
  v7 ---> v5
  v7 ---> v9
  v7 ---> v75
  v7 ---> v89
  v8 ---> v2
  v8 ---> v4
  v8 ---> v5
  v8 ---> v6
  v8 ---> v7
  v8 ---> v9
  v8 ---> v76
  v8 ---> v89
  v8 ---> v90
  v9 ---> v71
  v10 ---> v60
  v11 ---> v71
  v12 ---> v4
  v12 ---> v19
  v12 ---> v72
  v13 ---> v71
  v14 ---> v2
  v14 ---> v13
  v14 ---> v75
  v14 ---> v89
  v15 ---> v2
  v15 ---> v4
  v15 ---> v13
  v15 ---> v14
  v15 ---> v16
  v15 ---> v76
  v15 ---> v89
  v15 ---> v90
  v16 ---> v4
  v16 ---> v21
  v16 ---> v72
  v17 ---> v3
  v17 ---> v5
  v17 ---> v18
  v17 ---> v29
  v18 ---> v3
  v18 ---> v5
  v18 ---> v30
  v19 ---> v3
  v19 ---> v11
  v19 ---> v20
  v19 ---> v29
  v20 ---> v3
  v20 ---> v11
  v20 ---> v30
  v21 ---> v3
  v21 ---> v13
  v21 ---> v22
  v21 ---> v29
  v22 ---> v3
  v22 ---> v13
  v22 ---> v30
  v23 ---> v3
  v23 ---> v24
  v23 ---> v29
  v23 ---> v43
  v24 ---> v3
  v24 ---> v30
  v24 ---> v43
  v25 ---> v3
  v25 ---> v26
  v25 ---> v29
  v25 ---> v47
  v26 ---> v3
  v26 ---> v30
  v26 ---> v47
  v27 ---> v3
  v27 ---> v28
  v27 ---> v29
  v27 ---> v51
  v28 ---> v3
  v28 ---> v30
  v28 ---> v51
  v29 ---> v3
  v29 ---> v30
  v29 ---> v71
  v30 ---> v3
  v30 ---> v10
  v31 ---> v32
  v31 ---> v60
  v31 ---> v71
  v32 ---> v71
  v33 ---> v71
  v34 ---> v2
  v34 ---> v33
  v34 ---> v75
  v34 ---> v89
  v35 ---> v2
  v35 ---> v4
  v35 ---> v33
  v35 ---> v34
  v35 ---> v76
  v35 ---> v89
  v35 ---> v90
  v36 ---> v4
  v36 ---> v32
  v36 ---> v72
  v37 ---> v3
  v38 ---> v4
  v38 ---> v37
  v39 ---> v71
  v39 ---> v75
  v40 ---> v4
  v40 ---> v39
  v40 ---> v71
  v40 ---> v72
  v40 ---> v76
  v41 ---> v75
  v41 ---> v89
  v41 ---> v92
  v42 ---> v4
  v42 ---> v41
  v42 ---> v76
  v42 ---> v89
  v42 ---> v90
  v42 ---> v92
  v42 ---> v93
  v43 ---> v71
  v44 ---> v4
  v44 ---> v23
  v44 ---> v72
  v45 ---> v2
  v45 ---> v43
  v45 ---> v75
  v45 ---> v89
  v46 ---> v2
  v46 ---> v4
  v46 ---> v43
  v46 ---> v44
  v46 ---> v45
  v46 ---> v76
  v46 ---> v89
  v46 ---> v90
  v47 ---> v71
  v48 ---> v4
  v48 ---> v25
  v48 ---> v72
  v49 ---> v2
  v49 ---> v47
  v49 ---> v75
  v49 ---> v89
  v50 ---> v2
  v50 ---> v4
  v50 ---> v47
  v50 ---> v48
  v50 ---> v49
  v50 ---> v76
  v50 ---> v89
  v50 ---> v90
  v51 ---> v71
  v52 ---> v4
  v52 ---> v27
  v52 ---> v72
  v53 ---> v51
  v53 ---> v71
  v53 ---> v75
  v54 ---> v4
  v54 ---> v51
  v54 ---> v52
  v54 ---> v53
  v54 ---> v71
  v54 ---> v72
  v54 ---> v76
  v55 ---> v75
  v55 ---> v77
  v55 ---> v78
  v56 ---> v4
  v56 ---> v55
  v56 ---> v76
  v56 ---> v77
  v56 ---> v78
  v56 ---> v79
  v56 ---> v80
  v57 ---> v58
  v57 ---> v60
  v58 ---> v60
  v59 ---> v60
  v59 ---> v65
  v59 ---> v75
  v60 ---> v96
  v60 ---> v61
  v60 ---> v86
  v61 ---> v96
  v62 ---> v71
  v63 ---> v2
  v63 ---> v62
  v63 ---> v71
  v63 ---> v75
  v64 ---> v2
  v64 ---> v4
  v64 ---> v62
  v64 ---> v63
  v64 ---> v71
  v64 ---> v72
  v64 ---> v76
  v65 ---> v60
  v65 ---> v75
  v66 ---> v71
  v67 ---> v4
  v67 ---> v66
  v67 ---> v72
  v68 ---> v11
  v68 ---> v37
  v68 ---> v71
  v68 ---> v75
  v69 ---> v4
  v69 ---> v11
  v69 ---> v12
  v69 ---> v37
  v69 ---> v68
  v69 ---> v70
  v69 ---> v71
  v69 ---> v72
  v69 ---> v76
  v70 ---> v38
  v71 ---> v3
  v72 ---> v4
  v72 ---> v71
  v73 ---> v75
  v73 ---> v87
  v73 ---> v89
  v74 ---> v4
  v74 ---> v73
  v74 ---> v76
  v74 ---> v87
  v74 ---> v88
  v74 ---> v89
  v74 ---> v90
  v75 ---> v57
  v76 ---> v59
  v76 ---> v60
  v76 ---> v65
  v76 ---> v75
  v76 ---> v76
  v77 ---> v71
  v77 ---> v78
  v78 ---> v71
  v79 ---> v4
  v79 ---> v72
  v79 ---> v78
  v80 ---> v4
  v80 ---> v72
  v80 ---> v77
  v80 ---> v78
  v80 ---> v79
  v81 ---> v2
  v81 ---> v32
  v81 ---> v71
  v81 ---> v75
  v82 ---> v2
  v82 ---> v4
  v82 ---> v32
  v82 ---> v36
  v82 ---> v71
  v82 ---> v72
  v82 ---> v76
  v82 ---> v81
  v83 ---> v75
  v83 ---> v87
  v83 ---> v89
  v84 ---> v4
  v84 ---> v76
  v84 ---> v83
  v84 ---> v87
  v84 ---> v88
  v84 ---> v89
  v84 ---> v90
  v85 ---> v60
  v85 ---> v61
  v85 ---> v85
  v86 ---> v61
  v87 ---> v71
  v88 ---> v4
  v88 ---> v72
  v88 ---> v87
  v89 ---> v32
  v90 ---> v4
  v90 ---> v36
  v90 ---> v89
  v91 ---> v32
  v92 ---> v71
  v93 ---> v4
  v93 ---> v72
  v93 ---> v92
  v94 ---> v71
  v94 ---> v75
  v94 ---> v92
  v95 ---> v4
  v95 ---> v71
  v95 ---> v72
  v95 ---> v76
  v95 ---> v92
  v95 ---> v93
  v95 ---> v94
