---
config:
  theme: default
  look: classic
  flowchart:
    defaultRenderer: "elk"
title: procedures
---
flowchart TB
  v0@{shape: rounded, label: "aliquoting_procedures"}
  style v0 rx: 3px, ry: 3px 
  v1@{shape: rounded, label: "ball_mill_procedures"}
  style v1 rx: 3px, ry: 3px 
  v2@{shape: rounded, label: "centrifuge_procedures"}
  style v2 rx: 3px, ry: 3px 
  v3@{shape: rounded, label: "container_sealing_procedures"}
  style v3 rx: 3px, ry: 3px 
  v4@{shape: rounded, label: "disposal_procedures"}
  style v4 rx: 3px, ry: 3px 
  v5@{shape: rounded, label: "fractioning_procedures"}
  style v5 rx: 3px, ry: 3px 
  v6@{shape: rounded, label: "freeze_drying_procedures"}
  style v6 rx: 3px, ry: 3px 
  v7@{shape: rounded, label: "freezing_procedures"}
  style v7 rx: 3px, ry: 3px 
  v8@{shape: rounded, label: "geopositioning_procedures"}
  style v8 rx: 3px, ry: 3px 
  v9@{shape: rounded, label: "harvesting_procedures"}
  style v9 rx: 3px, ry: 3px 
  v10@{shape: rounded, label: "packaging_procedures"}
  style v10 rx: 3px, ry: 3px 
  v11@{shape: rounded, label: "photograph_procedures"}
  style v11 rx: 3px, ry: 3px 
  v12@{shape: rounded, label: "pouring_procedures"}
  style v12 rx: 3px, ry: 3px 
  v13@{shape: rounded, label: "storage_procedures"}
  style v13 rx: 3px, ry: 3px 
  v14@{shape: rounded, label: "supernatant_procedures"}
  style v14 rx: 3px, ry: 3px 
  v15@{shape: rounded, label: "weighing_procedures"}
  style v15 rx: 3px, ry: 3px 
  v16@{shape: rounded, label: "procedures"}
  style v16 rx: 3px, ry: 3px 
  v0 ---> v16
  v1 ---> v16
  v2 ---> v16
  v3 ---> v16
  v4 ---> v16
  v5 ---> v16
  v6 ---> v16
  v7 ---> v16
  v8 ---> v16
  v9 ---> v16
  v10 ---> v16
  v11 ---> v16
  v12 ---> v16
  v13 ---> v16
  v14 ---> v16
  v15 ---> v16
  v16 ---> v16
