---
config:
  layout: elk
  theme: default
  look: classic
title: Workspace Dependencies
---
erDiagram
  direction TB
  v2["asset compatibility rules"]
  v3["asset model ancestors"]
  v11["brands"]
  v32["container compatibility rules"]
  v42["entities DAG"]
  v60["next procedure templates"]
  v61["ownable tables"]
  v63["owner grants"]
  v68["parent procedure templates"]
  v76["privacy dependencies"]
  v77["procedure asset models"]
  v78["procedure template asset models"]
  v81["reused procedure template asset models"]
  v82["roles"]
  v91["table names"]
  v92["team members"]
  v94["tombstones"]
  v42 ||--|| v78 : "depends on"
  v42 ||--|| v81 : "depends on"
  v42 ||--|| v77 : "depends on"
  v2 ||--|| v42 : "depends on"
  v3 ||--|| v42 : "depends on"
  v11 ||--|| v42 : "depends on"
  v32 ||--|| v42 : "depends on"
  v42 ||--|| v82 : "depends on"
  v42 ||--|| v91 : "depends on"
  v60 ||--|| v68 : "depends on"
  v60 ||--|| v42 : "depends on"
  v42 ||--|| v61 : "depends on"
  v63 ||--|| v42 : "depends on"
  v63 ||--|| v82 : "depends on"
  v68 ||--|| v42 : "depends on"
  v76 ||--|| v42 : "depends on"
  v77 ||--|| v3 : "depends on"
  v77 ||--|| v78 : "depends on"
  v81 ||--|| v78 : "depends on"
  v92 ||--|| v42 : "depends on"
  v94 ||--|| v91 : "depends on"
